"""Mock data for demo purposes when scrapers fail or during development."""
from datetime import datetime, timedelta
from models import Job

def get_mock_jobs():
    now = datetime.utcnow()
    return [
        Job(
            id="mock-001",
            title="Senior React Developer for SaaS Dashboard",
            title_zh="資深 React 開發者 - SaaS 儀表板",
            description="We need an experienced React developer to build a complex analytics dashboard for our B2B SaaS product. Must have experience with D3.js, TypeScript, and state management (Redux/Zustand). Remote-friendly team.",
            description_zh="我們需要有經驗的 React 開發者為 B2B SaaS 產品建立複雜的分析儀表板。需具備 D3.js、TypeScript 和狀態管理經驗。",
            source="remoteok",
            source_url="https://remoteok.com/remote-jobs/123456",
            budget_min=3000,
            budget_max=6000,
            currency="USD",
            skills=["React", "TypeScript", "D3.js", "Redux", "Node.js"],
            category="技術開發",
            posted_at=now - timedelta(hours=3),
            ai_score=9.2,
            ai_reason="與您的 React/TypeScript 技能完全匹配，預算範圍理想",
            is_remote=True,
        ),
        Job(
            id="mock-002",
            title="Python FastAPI Backend Developer",
            title_zh="Python FastAPI 後端開發者",
            description="Looking for a Python developer proficient in FastAPI, SQLAlchemy, and PostgreSQL to build RESTful APIs for our fintech startup. 3-6 month contract with possibility of extension.",
            description_zh="尋找熟悉 FastAPI、SQLAlchemy 和 PostgreSQL 的 Python 開發者，為金融科技新創公司建立 RESTful API。",
            source="freelancer",
            source_url="https://www.freelancer.com/projects/python/fastapi-backend-developer",
            budget_min=2500,
            budget_max=5000,
            currency="USD",
            skills=["Python", "FastAPI", "PostgreSQL", "Docker", "AWS"],
            category="技術開發",
            posted_at=now - timedelta(hours=8),
            ai_score=8.7,
            ai_reason="Python 開發專案與您技能高度吻合，預算合理",
            is_remote=True,
        ),
        Job(
            id="mock-003",
            title="UI/UX Designer for Mobile App Redesign",
            title_zh="行動應用重新設計 UI/UX 設計師",
            description="Redesign our existing iOS/Android app with modern UI patterns. Need expertise in Figma, user research, prototyping, and design systems. The app serves 100k+ users.",
            description_zh="使用現代 UI 模式重新設計 iOS/Android 應用程式。需要 Figma 專業知識、用戶研究和設計系統經驗。",
            source="weworkremotely",
            source_url="https://weworkremotely.com/remote-jobs/456789",
            budget_min=2000,
            budget_max=4500,
            currency="USD",
            skills=["Figma", "UI/UX", "Prototyping", "Design Systems", "Mobile"],
            category="設計創意",
            posted_at=now - timedelta(hours=12),
            ai_score=7.5,
            ai_reason="設計工作雖不是您的主要偏好，但預算和遠端條件不錯",
            is_remote=True,
        ),
        Job(
            id="mock-004",
            title="全端工程師 - 電商平台開發",
            title_zh="全端工程師 - 電商平台開發",
            description="台灣電商新創公司徵求全端工程師，技術棧包含 Next.js、Node.js、MySQL。需開發購物車、金流整合、後台管理系統。可遠端工作，月薪 10-15 萬台幣。",
            source="104",
            source_url="https://www.104.com.tw/job/abc123",
            budget_min=100000,
            budget_max=150000,
            currency="TWD",
            skills=["Next.js", "Node.js", "MySQL", "React", "TypeScript"],
            category="技術開發",
            posted_at=now - timedelta(hours=5),
            ai_score=8.9,
            ai_reason="台灣電商平台，技術棧與您的 React/Node.js 技能完全匹配",
            is_remote=True,
        ),
        Job(
            id="mock-005",
            title="Content Marketing Manager - Tech Startup",
            title_zh="科技新創內容行銷經理",
            description="We're looking for a content marketing manager to drive our blog, email campaigns, and social media presence. Must have B2B SaaS experience and strong SEO knowledge.",
            source="weworkremotely",
            source_url="https://weworkremotely.com/remote-jobs/789012",
            budget_min=4000,
            budget_max=7000,
            currency="USD",
            skills=["Content Marketing", "SEO", "Email Marketing", "Copywriting"],
            category="行銷文案",
            posted_at=now - timedelta(hours=18),
            ai_score=5.3,
            ai_reason="行銷職位與您偏好的技術類別不符",
            is_remote=True,
        ),
        Job(
            id="mock-006",
            title="TypeScript / Node.js API Developer",
            title_zh="TypeScript / Node.js API 開發者",
            description="Build microservices for our platform using Node.js, TypeScript, and gRPC. Experience with Kafka, Redis, and distributed systems required. Contract role, 6 months.",
            description_zh="使用 Node.js、TypeScript 和 gRPC 為我們的平台建立微服務。需要 Kafka、Redis 和分佈式系統經驗。",
            source="remoteok",
            source_url="https://remoteok.com/remote-jobs/234567",
            budget_min=5000,
            budget_max=8000,
            currency="USD",
            skills=["TypeScript", "Node.js", "gRPC", "Kafka", "Redis", "Docker"],
            category="技術開發",
            posted_at=now - timedelta(hours=24),
            ai_score=9.5,
            ai_reason="TypeScript/Node.js 技能完美匹配，薪資高且遠端友好",
            is_remote=True,
        ),
        Job(
            id="mock-007",
            title="品牌視覺設計師 - 新創公司",
            title_zh="品牌視覺設計師 - 新創公司",
            description="台灣新創公司尋求品牌視覺設計師，負責公司識別、宣傳材料、社群媒體素材設計。需熟悉 Figma、Illustrator、Photoshop。",
            source="104",
            source_url="https://www.104.com.tw/job/def456",
            budget_min=60000,
            budget_max=90000,
            currency="TWD",
            skills=["Figma", "Illustrator", "Photoshop", "品牌設計", "UI設計"],
            category="設計創意",
            posted_at=now - timedelta(hours=36),
            ai_score=6.8,
            ai_reason="設計工作台灣在地機會，但非您主要技術方向",
            is_remote=True,
        ),
        Job(
            id="mock-008",
            title="Machine Learning Engineer - NLP Focus",
            title_zh="機器學習工程師 - NLP 專注",
            description="Join our AI team to build NLP models for document classification and entity extraction. Python, PyTorch, Transformers/HuggingFace required. Competitive compensation.",
            description_zh="加入我們的 AI 團隊，構建用於文件分類和實體抽取的 NLP 模型。",
            source="remoteok",
            source_url="https://remoteok.com/remote-jobs/345678",
            budget_min=6000,
            budget_max=10000,
            currency="USD",
            skills=["Python", "PyTorch", "NLP", "HuggingFace", "Machine Learning"],
            category="技術開發",
            posted_at=now - timedelta(hours=6),
            ai_score=7.8,
            ai_reason="Python AI 專案，技能部分匹配，報酬優秀",
            is_remote=True,
        ),
        Job(
            id="mock-009",
            title="English to Chinese Technical Translator",
            title_zh="英中技術文件翻譯員",
            description="Translate technical documentation, API docs, and user guides from English to Traditional Chinese. Must have background in software/IT. Per-word rate: $0.10-0.15.",
            description_zh="將技術文件、API 文檔和用戶指南從英文翻譯成繁體中文。需要軟體/IT 背景。",
            source="freelancer",
            source_url="https://www.freelancer.com/projects/translation/english-chinese-technical",
            budget_min=500,
            budget_max=2000,
            currency="USD",
            skills=["Translation", "Technical Writing", "Chinese", "English"],
            category="翻譯文字",
            posted_at=now - timedelta(hours=10),
            ai_score=6.0,
            ai_reason="翻譯工作預算偏低，但有技術背景加分",
            is_remote=True,
        ),
        Job(
            id="mock-010",
            title="DevOps Engineer - AWS Infrastructure",
            title_zh="DevOps 工程師 - AWS 基礎架構",
            description="Set up and maintain CI/CD pipelines, manage AWS infrastructure with Terraform, implement monitoring with Datadog. 6-month contract, $80-100/hr.",
            description_zh="建立和維護 CI/CD 管道，使用 Terraform 管理 AWS 基礎架構，使用 Datadog 實施監控。",
            source="weworkremotely",
            source_url="https://weworkremotely.com/remote-jobs/890123",
            budget_min=5500,
            budget_max=7500,
            currency="USD",
            skills=["AWS", "Docker", "Kubernetes", "Terraform", "CI/CD", "Datadog"],
            category="技術開發",
            posted_at=now - timedelta(hours=15),
            ai_score=8.1,
            ai_reason="DevOps 雲端專案，與系統技能相符，報酬競爭力強",
            is_remote=True,
        ),
        Job(
            id="mock-011",
            title="Shopify Developer for E-commerce Store",
            title_zh="電商網站 Shopify 開發者",
            description="Custom Shopify theme development and app integrations for a fashion e-commerce brand. Need Liquid templating, JavaScript, and Shopify API experience.",
            description_zh="為時尚電商品牌開發自定義 Shopify 主題和應用程式整合。",
            source="freelancer",
            source_url="https://www.freelancer.com/projects/shopify/developer-ecommerce",
            budget_min=1500,
            budget_max=3500,
            currency="USD",
            skills=["Shopify", "JavaScript", "HTML", "CSS", "Liquid"],
            category="技術開發",
            posted_at=now - timedelta(hours=20),
            ai_score=7.2,
            ai_reason="Shopify 開發前端技能匹配，預算中等",
            is_remote=True,
        ),
        Job(
            id="mock-012",
            title="SEO 內容策略師 - 科技媒體",
            title_zh="SEO 內容策略師 - 科技媒體",
            description="科技媒體網站尋求 SEO 內容策略師，負責關鍵字研究、內容規劃、文章優化。需熟悉 Google Analytics、Search Console、SEMrush。月薪 5-8 萬。",
            source="104",
            source_url="https://www.104.com.tw/job/ghi789",
            budget_min=50000,
            budget_max=80000,
            currency="TWD",
            skills=["SEO", "Content Strategy", "Google Analytics", "SEMrush"],
            category="行銷文案",
            posted_at=now - timedelta(hours=8),
            ai_score=4.5,
            ai_reason="行銷類別非您主要偏好，與技術技能不符",
            is_remote=True,
        ),
        Job(
            id="mock-013",
            title="Vue.js Frontend Developer",
            title_zh="Vue.js 前端開發者",
            description="Build modern web applications using Vue 3, Pinia, and Vite. Work with our design team to implement pixel-perfect UIs. Experience with Vue Router and TypeScript preferred.",
            description_zh="使用 Vue 3、Pinia 和 Vite 建立現代網頁應用程式。",
            source="remoteok",
            source_url="https://remoteok.com/remote-jobs/456789",
            budget_min=3500,
            budget_max=6500,
            currency="USD",
            skills=["Vue.js", "TypeScript", "Pinia", "Vite", "JavaScript"],
            category="技術開發",
            posted_at=now - timedelta(hours=4),
            ai_score=8.4,
            ai_reason="Vue.js 前端開發，技術棧現代，報酬合理",
            is_remote=True,
        ),
        Job(
            id="mock-014",
            title="Motion Graphics Designer",
            title_zh="動態圖形設計師",
            description="Create engaging motion graphics and animations for social media, product demos, and marketing videos. Proficiency in After Effects, Premiere Pro required.",
            description_zh="為社群媒體、產品展示和行銷影片創建引人入勝的動態圖形和動畫。",
            source="weworkremotely",
            source_url="https://weworkremotely.com/remote-jobs/901234",
            budget_min=3000,
            budget_max=5500,
            currency="USD",
            skills=["After Effects", "Premiere Pro", "Motion Design", "Animation"],
            category="設計創意",
            posted_at=now - timedelta(hours=28),
            ai_score=5.8,
            ai_reason="設計工作報酬尚可，但不在您的偏好分類中",
            is_remote=True,
        ),
        Job(
            id="mock-015",
            title="React Native Mobile Developer",
            title_zh="React Native 行動應用開發者",
            description="Develop cross-platform mobile apps using React Native. Must have published apps on App Store/Google Play. Experience with native modules and performance optimization.",
            description_zh="使用 React Native 開發跨平台行動應用程式。需有在 App Store/Google Play 發布應用的經驗。",
            source="freelancer",
            source_url="https://www.freelancer.com/projects/mobile/react-native-developer",
            budget_min=4000,
            budget_max=7000,
            currency="USD",
            skills=["React Native", "React", "TypeScript", "iOS", "Android"],
            category="技術開發",
            posted_at=now - timedelta(hours=11),
            ai_score=9.0,
            ai_reason="React Native 與您的 React 技能高度相關，薪資優秀",
            is_remote=True,
        ),
        Job(
            id="mock-016",
            title="資深後端工程師 - 金融科技",
            title_zh="資深後端工程師 - 金融科技",
            description="金融科技公司徵求資深後端工程師，負責支付系統、清算系統開發。技術棧：Java Spring Boot、PostgreSQL、Redis、Kafka。提供股票選擇權。",
            source="104",
            source_url="https://www.104.com.tw/job/jkl012",
            budget_min=120000,
            budget_max=180000,
            currency="TWD",
            skills=["Java", "Spring Boot", "PostgreSQL", "Redis", "Kafka"],
            category="技術開發",
            posted_at=now - timedelta(hours=14),
            ai_score=7.5,
            ai_reason="金融科技後端，Java 技術棧，薪資高但非主要技能方向",
            is_remote=True,
        ),
        Job(
            id="mock-017",
            title="WordPress Developer & Designer",
            title_zh="WordPress 開發設計師",
            description="Build custom WordPress themes and plugins for a digital agency. Clients range from restaurants to law firms. PHP, MySQL, ACF, Elementor experience needed.",
            description_zh="為數位代理商建立自定義 WordPress 主題和插件。",
            source="remoteok",
            source_url="https://remoteok.com/remote-jobs/567890",
            budget_min=2000,
            budget_max=4000,
            currency="USD",
            skills=["WordPress", "PHP", "MySQL", "Elementor", "HTML", "CSS"],
            category="技術開發",
            posted_at=now - timedelta(hours=32),
            ai_score=6.5,
            ai_reason="WordPress 開發匹配部分技能，報酬中等",
            is_remote=True,
        ),
        Job(
            id="mock-018",
            title="Japanese-Chinese Interpreter for Tech Conference",
            title_zh="科技會議日中口譯員",
            description="Need Japanese-Chinese interpreter for a 3-day tech conference in Taipei. Simultaneous interpretation for AI and blockchain sessions. JLPT N1 required.",
            description_zh="需要日中口譯員參加台北為期 3 天的科技會議。",
            source="104",
            source_url="https://www.104.com.tw/job/mno345",
            budget_min=15000,
            budget_max=30000,
            currency="TWD",
            skills=["Translation", "Japanese", "Chinese", "Interpretation"],
            category="翻譯文字",
            posted_at=now - timedelta(hours=22),
            ai_score=4.0,
            ai_reason="翻譯工作預算偏低，且不在主要技能範疇",
            is_remote=False,
        ),
        Job(
            id="mock-019",
            title="Full Stack Developer - Next.js & GraphQL",
            title_zh="全端開發者 - Next.js & GraphQL",
            description="Join our team to build a next-gen e-learning platform with Next.js, GraphQL, and Prisma. Remote-first culture, competitive pay, stock options available for long-term contractors.",
            description_zh="加入我們的團隊，使用 Next.js、GraphQL 和 Prisma 建立下一代 e-learning 平台。",
            source="weworkremotely",
            source_url="https://weworkremotely.com/remote-jobs/012345",
            budget_min=5500,
            budget_max=9000,
            currency="USD",
            skills=["Next.js", "React", "GraphQL", "TypeScript", "Prisma", "PostgreSQL"],
            category="技術開發",
            posted_at=now - timedelta(hours=2),
            ai_score=9.8,
            ai_reason="Next.js/React/TypeScript 技能完美匹配，薪資優秀且遠端優先",
            is_remote=True,
        ),
        Job(
            id="mock-020",
            title="Digital Marketing Specialist - B2B SaaS",
            title_zh="B2B SaaS 數位行銷專員",
            description="Drive demand generation for our B2B SaaS product through SEO, content marketing, LinkedIn ads, and email campaigns. Hubspot and Google Ads experience required.",
            description_zh="通過 SEO、內容行銷、LinkedIn 廣告和電子郵件活動推動 B2B SaaS 產品的需求生成。",
            source="remoteok",
            source_url="https://remoteok.com/remote-jobs/678901",
            budget_min=4500,
            budget_max=7500,
            currency="USD",
            skills=["SEO", "Google Ads", "HubSpot", "LinkedIn Ads", "Content Marketing"],
            category="行銷文案",
            posted_at=now - timedelta(hours=16),
            ai_score=4.8,
            ai_reason="行銷職位與技術背景不符，但預算尚可",
            is_remote=True,
        ),
        Job(
            id="mock-021",
            title="Data Engineer - dbt & Airflow",
            title_zh="資料工程師 - dbt & Airflow",
            description="Build and maintain data pipelines using dbt, Airflow, and Snowflake. Transform raw data into business insights. Python and SQL expertise required. Fully remote.",
            description_zh="使用 dbt、Airflow 和 Snowflake 建立和維護資料管道。",
            source="remoteok",
            source_url="https://remoteok.com/remote-jobs/789012",
            budget_min=6000,
            budget_max=9500,
            currency="USD",
            skills=["Python", "SQL", "dbt", "Airflow", "Snowflake", "AWS"],
            category="技術開發",
            posted_at=now - timedelta(hours=7),
            ai_score=8.6,
            ai_reason="Python 資料工程，技能匹配度高，薪資競爭力強",
            is_remote=True,
        ),
        Job(
            id="mock-022",
            title="UI Designer - Design System Creation",
            title_zh="UI 設計師 - 設計系統建立",
            description="Create and document a comprehensive design system from scratch for our SaaS platform. Figma expertise required. Must have experience with component libraries and design tokens.",
            description_zh="為 SaaS 平台從頭建立和記錄完整的設計系統。需要 Figma 專業知識。",
            source="freelancer",
            source_url="https://www.freelancer.com/projects/design/ui-design-system",
            budget_min=3000,
            budget_max=6000,
            currency="USD",
            skills=["Figma", "Design Systems", "UI Design", "Component Library"],
            category="設計創意",
            posted_at=now - timedelta(hours=9),
            ai_score=6.2,
            ai_reason="設計系統工作報酬不錯，但設計非您的主要技能",
            is_remote=True,
        ),
    ]
